# Simple workflow for deploying static content to GitHub Pages
name: Cross Compile cpp for amd64 Architecture

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  cross-compile-cpp-amd64:
    environment:
      name: cross-compile-cpp-amd64
    runs-on: ubuntu-latest
    steps:
      # Check YOUR project out!
      - name: "Check out repository"
        uses: actions/checkout@v2

      # Apply requirements on ubuntu
      - name: "Install requirements"
        run: |
          sudo apt update
          sudo apt install -y cmake:amd64 libboost-all-dev:amd64 libyaml-cpp-dev:amd64

      # Compile for amd64
      - name: "Compile for amd64"
        run: |
          cd tool/cpp
          bash build.sh

      # Package
      - name: "Package"
        run: |
          cd tool/cpp
          mkdir -p pacmon-cpp-amd64/usr/bin
          cp build/src/main/main pacmon-cpp-amd64/usr/bin/pacmon
          tar cfz pacmon-cpp-amd64.tar.gz pacmon-cpp-amd64

      # Upload the results to the CI.
      - uses: actions/upload-artifact@v2
        with:
          name: pacmon-cpp-amd64
          path: tool/cpp/pacmon-cpp-amd64.tar.gz
