# Simple workflow for deploying static content to GitHub Pages
name: Run Doxygen on cpp codebase

on:
  # Runs on pushes targeting the default branch
  push:
    branches: []

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  doxygen:
    environment:
      name: doxygen
    runs-on: ubuntu-latest
    steps:
      # Check YOUR project out!
      - name: "Check out repository"
        uses: actions/checkout@v2

        # Runs doxygen
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: 'tool/cpp'
          doxyfile-path: 'Doxyfile'

            # Upload the results to the CI.
      - uses: actions/upload-artifact@v2
        with:
          name: "Doxygen HTML Documentation"
          path: tool/cpp/html
